Display cluster name
openshift/osd-alert-analysis pull request #10
Opened 2022-06-27 03:50 UTC by anispate

Adding an option to display the cluster name for the question "Which alerts fire more than once per on-call shift (in the same cluster)?"

It will print the cluster name rather than the cluster ID

2022-06-30 13:35 UTC, aweiteka commented
@anispate could you add a screenshot that demonstrates this UI change?

2022-06-30 18:05 UTC, anispate commented
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/102506997/176746987-30d77c47-d327-4a9f-bfb2-c894b213db6e.png">

Hi Aaron,

PFA to view the image for the UI Change

2022-06-30 18:13 UTC, fahlmant commented
@anispate Looks like the style test is failing

2022-06-30 18:17 UTC, aweiteka commented
Looks good. FWIW, the "osd-" string prefix not technically part of the cluster name. I'm not sure if it's worth the effort to remove it.

2022-06-30 18:20 UTC, fahlmant commented
I don't think Zabbix is the correct title for this either

2022-06-30 19:11 UTC, abyrne55 commented
/retest

2022-06-30 21:00 UTC, abyrne55 requested changes

2022-06-30 21:00 UTC, abyrne55 commented on models.py
> +from sqlalchemy import func
This was my bad for telling you to add this import, as I didn't realize we already imported `func` on line 23 (we just rename it to `sqlfunc`). Could you remove this import and replace your use of `func` on line 174 with `sqlfunc`?

Once that's done, remove the `[WIP]` from this PR's title, and it'll be ready to review.

2022-07-01 12:00 UTC, abyrne55 commented
/label tide/merge-method-squash

2022-07-01 12:58 UTC, fahlmant commented
@anispate Can you please squash the commits?

2022-07-07 14:06 UTC, ritmun commented on questions.py
> +        self._column_names = ["ID", "Cluster", "Alert", "namespace", "urgency", "flaps"]
nit: could we stick to the same casing for all column names? e.g. "namespace", "urgency", "flaps" are all lowercase.

2022-07-07 14:10 UTC, ritmun commented
Left one nit. One more nit: Should we call the column "service" instead of "Cluster name", since that is honestly what we're using? Sometimes the service maybe dead man snitch which isn't really a cluster name.

2022-07-07 14:25 UTC, anispate commented on questions.py
> +        self._column_names = ["ID", "Cluster", "Alert", "namespace", "urgency", "flaps"]
Okay thats a good point. Let me make that change

2022-07-07 15:14 UTC, ritmun commented
/lgtm

2022-07-07 19:50 UTC, abyrne55 approved these changes
/approve

Tested locally and confirmed proper operation. Nice work, @anispate, and thanks for the PR!

2022-07-07 19:56 UTC, merged